export const typography = {
  family: "'Poppins', sans-serif",
  title: {
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 300,
    fontSize: "6rem",
    lineHeight: 1.167,
    letterSpacing: "-0.01562rem",
    margin: 0,
  },
  subTitle: {
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 300,
    fontSize: "3.75rem",
    lineHeight: 1.2,
    letterSpacing: "-0.00833rem",
    margin: 0,
  },
  button: {
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 500,
    fontSize: "0.875rem",
    lineHeight: 1.75,
    letterSpacing: "0.02857rem",
    textTransform: "uppercase",
  },
  link: {
    fontFamily: "'Poppins', sans-serif",
    fontWeight: 500,
    fontSize: "0.875rem",
    lineHeight: 1.75,
    letterSpacing: "0.02857rem",
    textTransform: "uppercase",
    textDecoration: "underline",
  },
};
